### PR TITLE
Created a wifi example

### PR DESCRIPTION
**Pull request by n-elia**
Hi! I propose you to add this basic example into the Advanced folder.
It is nothing more than your `OTASketchDownload` example sketch, enabled to work over WiFi using the official WiFiNINA library.
It can work over HTTP or over HTTPS.
Use case example: wirelessly fetch the updates in IoT scenarios where the device is far away.
Tested and working with Arduino Nano 33 IoT.

### CODE REVIEW

**Comment by jandrassy** [comment]
thank you. please modify the example to use "arduino_secrets.h" as the WiFi101_OTA example and WiFiNINA examples

**Comment by n-elia** [comment]
Thank you. I moved the secrets on the external `arduino_secrets.h` file as requested, it should be OK now.
Again, tested and working with Arduino Nano 33 IoT.

**Comment by jandrassy** [comment]
and please fix the check interval. it is 60 milliseconds now

**Comment by n-elia** [comment]
Ok, I improved that line.

**Pull request merged**
