### PR TITLE
Update WiFiOTA.cpp

### PR DESCRIPTION
**Pull request by figital**
Un-harcoding the username.

### CODE REVIEW

**Comment by jandrassy** [comment]
name is something else

**Comment by figital** [comment]
Why would the username be hardcoded to "arduino"?

**Comment by jandrassy** [comment]
> Why would the username be hardcoded to "arduino"?

there are no users. it is only one password.

**Comment by figital** [comment]
In the demo code for this library there is a username and a password .... (line 45).

https://github.com/jandrassy/ArduinoOTA/blob/master/examples/OTEthernet/OTEthernet.ino

... some users might not want to use this username. (We do not).

**Comment by jandrassy** [comment]
it is no a username. it is the name of the network port

**Comment by figital** [comment]
i see what you are saying. thank you for clarifying!

why shouldn't i be able to change the name of the network port?

**Comment by jandrassy** [comment]
> i see what you are saying. thank you for clarifying!
> 
> why shouldn't i be able to change the name of the network port?

if you have more arduinos with network port (and IP addresses assigned by DHCP)

**Pull request closed without merging**
