### PR TITLE
Avoid erasing all pages at once (takes looong time on some platforms)

### PR DESCRIPTION
**Pull request by vshymanskyy**
Areaseing all pages at once can take ~30 seconds on Micro:bit 2, and the board it unresponsive during this time, which leads to timeouts, etc.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
@JAndrassy what do you think?

**Comment by JAndrassy** [comment]
Hello Volodymyr

did you test it on SAMD21, SAMD51 too?

I would call erase at the beginning of `write` and remove the erase call from `open`.
why the `const nextAddress` variable?
why the recalculation of pageAlignedLength in `close`? and what is `* 4` there?

**Comment by vshymanskyy** [comment]
Honestly, I did this change quite some time ago, so I don't remember ;)
But, I'll be running this modified version of ArduinoOTA on a bunch of platforms soon (including SAMD) so I'll try to answer all the questions!

**Comment by vshymanskyy** [comment]
1. I'm erasing at the beginning of `write` now
2. `nextAddress` was removed
3. Now, on recalculation of `pageAlignedLength`...

This is needed in case the actually written binary is smaller than the size provided in open(). Why?
In some cases (i.e. compressed library, HTTP file upload) the size of the firmware binary is not known upfront. The firmware update can be achieved in such cases by calling:
```cpp
InternalStorage.open(InternalStorage.maxSize());
```
I've added some comments, and the `* 4` was changed to `* sizeof(uint32_t)` to make it easier to understand.

I've tested this version on multiple platforms:
 - nRF52840 (BLE Nano2): `OK`
 - nRF52833 (Micro:bit V2): `OK`
 - SAMD21G18A (Nano 22 IoT): `Failed`
 - SAMD51P19A (Wio Terminal): `Failed`
 
 Based on these tests, I changed the PR so that the page erasing strategy is changed only for nRF52 devices.
 
 @JAndrassy LMK your thoughts!

**Comment by JAndrassy** [comment]
I like it. Is it ready to merge or you want to change something on it yet?

**Comment by JAndrassy** [comment]
Volodymyr, let me know when you need a release of ArduinoOTA

**Comment by vshymanskyy** [comment]
No urgency! i can use it as is. Thanks ;)

**Pull request merged**
