### PR TITLE
Initial SAMD51 support

### LINKED ISSUE #53: Support for SAMD51
I am trying to add OTA update via wifi download from web to Flash for a SAMD51J20, specifically the Titano (https://learn.adafruit.com/adafruit-pyportal-titano).  Any pointers on how to do this would be appreciated.  

I am pretty basic in my skillset.

### PR DESCRIPTION
**Pull request by vshymanskyy**
Tested with Seeed Wio Terminal

Closes #53

### CODE REVIEW

**Comment by vshymanskyy** [comment]
@jandrassy please review, as I have only limited experience with SAMDx1 devices.

**Comment by vshymanskyy** [comment]
@jandrassy thanks for merging it.
Could you please also publish a new version of the library? Thanks!

**Comment by jandrassy** [comment]
@vshymanskyy Volodymyr, did you test the upload from IDE or only Edgent download to InternalStorage? 
the Seeed SAMD boards package has the configuration for OTA from IDE.
I will update README for SAMD51 if the upload from IDE works too.

**Comment by vshymanskyy** [comment]
No, I have only tested the HTTP download.

**Comment by jandrassy** [comment]
> Could you please also publish a new version of the library? Thanks!
done

**Comment by vshymanskyy** [comment]
Awesome, thank you!

**Pull request merged**
